name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read         # allow checkout
  pages: write           # allow deployment to GitHub Pages
  id-token: write        # required for older peaceiris action versions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
          publish_branch: gh-pages 